// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chqkxilivwzowspjwluz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNocWt4aWxpdnd6b3dzcGp3bHV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MzQ1NDQsImV4cCI6MjA2NTQxMDU0NH0.8guFG0BwzfJdTraTcWWLFftfQ_MbA6ON39SM5jFYSMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);